# Generated by Django 5.0.1 on 2024-02-02 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='IntRangeParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('minDefaultValue', models.IntegerField()),
                ('maxDefaultValue', models.IntegerField()),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.configuationitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
