# Generated by Django 5.0.1 on 2024-02-18 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ALifeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('simOutType', models.CharField(help_text="Wrote types separate with '/'", max_length=512)),
                ('transformerType', models.CharField(help_text="Wrote types separate with '/'", max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idHtml', models.CharField(max_length=128, null=True)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigurationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aLifeModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.alifemodel')),
            ],
        ),
        migrations.CreateModel(
            name='ColorParameter',
            fields=[
                ('parameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewer.parameter')),
                ('hexDefaultValue', models.CharField(max_length=7)),
            ],
            bases=('viewer.parameter',),
        ),
        migrations.CreateModel(
            name='NumberParameter',
            fields=[
                ('parameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewer.parameter')),
                ('defaultValue', models.FloatField()),
                ('step', models.FloatField()),
                ('minValue', models.FloatField(blank=True, null=True)),
                ('maxValue', models.FloatField(blank=True, null=True)),
            ],
            bases=('viewer.parameter',),
        ),
        migrations.CreateModel(
            name='NumberRangeParameter',
            fields=[
                ('parameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewer.parameter')),
                ('minDefaultValue', models.FloatField()),
                ('maxDefaultValue', models.FloatField()),
                ('step', models.FloatField()),
            ],
            bases=('viewer.parameter',),
        ),
        migrations.CreateModel(
            name='SelectionParameter',
            fields=[
                ('parameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewer.parameter')),
                ('options', models.CharField(help_text="Wrote options separate with '/'", max_length=512)),
            ],
            bases=('viewer.parameter',),
        ),
        migrations.CreateModel(
            name='RulesConfiguration',
            fields=[
                ('configurationitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewer.configurationitem')),
            ],
            bases=('viewer.configurationitem',),
        ),
        migrations.CreateModel(
            name='TransformerItem',
            fields=[
                ('configurationitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewer.configurationitem')),
            ],
            bases=('viewer.configurationitem',),
        ),
        migrations.AddField(
            model_name='parameter',
            name='configurationItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.configurationitem'),
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('aLifeModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.alifemodel')),
            ],
        ),
    ]
