# Generated by Django 5.0.1 on 2024-02-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationitem',
            name='name',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
