# Generated by Django 5.0.1 on 2024-02-02 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConfiguationItem',
            new_name='ConfigurationItem',
        ),
    ]
