# Generated by Django 5.0.1 on 2024-02-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_rename_configuationitem_configurationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='intrangeparameter',
            name='type',
            field=models.CharField(choices=[('IR', 'Intrange')], default='IR', max_length=3),
        ),
    ]
