# Generated by Django 5.0.1 on 2024-02-18 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_configurationitem_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alifemodel',
            name='transformerType',
        ),
        migrations.CreateModel(
            name='VisualizationInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('aLifeModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.alifemodel')),
                ('transformer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.transformeritem')),
            ],
        ),
    ]
