# Generated by Django 5.0.1 on 2024-02-07 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_intrangeparameter_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('hexDefaultValue', models.CharField(max_length=7)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.configurationitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NumberParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('defaultValue', models.FloatField()),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.configurationitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NumberRangeParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('minDefaultValue', models.FloatField()),
                ('maxDefaultValue', models.FloatField()),
                ('step', models.FloatField()),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.configurationitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SelectionParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('options', models.JSONField()),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.configurationitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='IntRangeParameter',
        ),
    ]
