# Generated by Django 5.0.1 on 2024-02-19 10:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_remove_alifemodel_transformertype_visualizationinput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationitem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
