# Generated by Django 5.0.1 on 2024-02-07 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_colorparameter_numberparameter_numberrangeparameter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ALifeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='configurationitem',
            name='aLifeModel',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='viewer.alifemodel'),
        ),
    ]
