# Generated by Django 5.0.1 on 2024-02-19 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_alter_configurationitem_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisualizationInput',
        ),
    ]
