# Generated by Django 5.0.1 on 2024-02-08 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_alter_selectionparameter_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorparameter',
            name='configuration',
        ),
        migrations.RemoveField(
            model_name='colorparameter',
            name='id',
        ),
        migrations.RemoveField(
            model_name='colorparameter',
            name='name',
        ),
        migrations.RemoveField(
            model_name='numberparameter',
            name='configuration',
        ),
        migrations.RemoveField(
            model_name='numberparameter',
            name='id',
        ),
        migrations.RemoveField(
            model_name='numberparameter',
            name='name',
        ),
        migrations.RemoveField(
            model_name='numberrangeparameter',
            name='configuration',
        ),
        migrations.RemoveField(
            model_name='numberrangeparameter',
            name='id',
        ),
        migrations.RemoveField(
            model_name='numberrangeparameter',
            name='name',
        ),
        migrations.RemoveField(
            model_name='selectionparameter',
            name='configuration',
        ),
        migrations.RemoveField(
            model_name='selectionparameter',
            name='id',
        ),
        migrations.RemoveField(
            model_name='selectionparameter',
            name='name',
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('NR', 'Numberrange'), ('NV', 'Numbervalue'), ('CV', 'Colorvalue'), ('SV', 'Selectionvalue')], max_length=3)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.configurationitem')),
            ],
        ),
        migrations.AddField(
            model_name='colorparameter',
            name='parameter_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewer.parameter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='numberparameter',
            name='parameter_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewer.parameter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='numberrangeparameter',
            name='parameter_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewer.parameter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selectionparameter',
            name='parameter_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewer.parameter'),
            preserve_default=False,
        ),
    ]
