# Generated by Django 5.0.1 on 2024-02-08 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_remove_colorparameter_configuration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='type',
        ),
    ]
