# Generated by Django 5.0.1 on 2024-02-12 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_remove_parameter_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('aLifeModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.alifemodel')),
            ],
        ),
    ]
