# Generated by Django 5.0.1 on 2024-02-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_configurationitem_idhtml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationitem',
            name='idHtml',
            field=models.CharField(max_length=128),
        ),
    ]
