# Generated by Django 5.0.1 on 2024-02-19 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0010_rename_idhtml_parameter_classhtml'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameter',
            old_name='classHtml',
            new_name='idHtml',
        ),
    ]
