# Generated by Django 5.0.1 on 2024-02-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0010_parameter_idhtml'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberparameter',
            name='maxValue',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='numberparameter',
            name='minValue',
            field=models.FloatField(null=True),
        ),
    ]
