# Generated by Django 5.0.1 on 2024-02-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0011_numberparameter_maxvalue_numberparameter_minvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberparameter',
            name='maxValue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='numberparameter',
            name='minValue',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
