# Generated by Django 5.0.1 on 2024-02-19 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0011_rename_classhtml_parameter_idhtml'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='idHtml',
        ),
    ]
