# Generated by Django 5.0.1 on 2024-02-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0012_alter_numberparameter_maxvalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alifemodel',
            name='simOutType',
            field=models.CharField(help_text="Wrote types separate with '/'", max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='alifemodel',
            name='transformerType',
            field=models.CharField(help_text="Wrote types separate with '/'", max_length=512, null=True),
        ),
    ]
