# Generated by Django 5.0.1 on 2024-02-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0012_remove_parameter_idhtml'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='paramId',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
