# Generated by Django 5.0.1 on 2024-02-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0013_alifemodel_simouttype_alifemodel_transformertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alifemodel',
            name='simOutType',
            field=models.CharField(help_text="Wrote types separate with '/'", max_length=512),
        ),
        migrations.AlterField(
            model_name='alifemodel',
            name='transformerType',
            field=models.CharField(help_text="Wrote types separate with '/'", max_length=512),
        ),
    ]
