# Generated by Django 5.0.1 on 2024-02-19 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0014_alter_alifemodel_simouttype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='textParameter',
            fields=[
                ('parameter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewer.parameter')),
                ('values', models.TextField(help_text="Write options separate with '/'", max_length=128)),
            ],
            bases=('viewer.parameter',),
        ),
        migrations.AlterField(
            model_name='selectionparameter',
            name='options',
            field=models.CharField(help_text="Write options separate with '/'", max_length=512),
        ),
    ]
