# Generated by Django 5.0.1 on 2024-02-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0014_selectionparameter_defaultvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformeritem',
            name='outputType',
            field=models.CharField(default='STATE_0', max_length=128),
        ),
        migrations.AddField(
            model_name='transformeritem',
            name='transformerType',
            field=models.CharField(default='COLOR', max_length=128),
        ),
    ]
