# Generated by Django 5.0.1 on 2024-02-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0015_transformeritem_outputtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformeritem',
            name='outputType',
            field=models.CharField(default='POSITION_X', max_length=128),
        ),
    ]
