# Generated by Django 5.0.1 on 2024-02-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0016_alter_transformeritem_outputtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='alifemodel',
            name='transformerType',
            field=models.CharField(default='POSITION_X/POSITION_Y/POSITION_Z/COULEUR', help_text="Wrote types separate with '/'", max_length=512),
            preserve_default=False,
        ),
    ]
