# Generated by Django 5.0.1 on 2024-02-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0017_alifemodel_transformertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformeritem',
            name='displayedByDefault',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transformeritem',
            name='isDeletable',
            field=models.BooleanField(default=True),
        ),
    ]
