# Generated by Django 5.0.1 on 2024-03-04 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0019_transformeritem_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='configurationItem',
        ),
        migrations.DeleteModel(
            name='RulesConfiguration',
        ),
    ]
