# Generated by Django 5.0.1 on 2024-03-04 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0020_remove_parameter_configurationitem_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransformerItem',
        ),
    ]
