# Generated by Django 5.0.1 on 2024-03-04 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0021_delete_transformeritem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfigurationItem',
        ),
    ]
