# Generated by Django 5.0.1 on 2024-03-04 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0022_delete_configurationitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransformerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idHtml', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024)),
                ('outputType', models.CharField(default='POSITION_X', max_length=128)),
                ('transformerType', models.CharField(default='COLOR', max_length=128)),
                ('displayedByDefault', models.BooleanField(default=True)),
                ('isDeletable', models.BooleanField(default=True)),
                ('aLifeModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.alifemodel')),
            ],
        ),
    ]
