# Generated by Django 5.0.1 on 2024-03-04 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0023_transformeritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='configurationItem',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='viewer.transformeritem'),
            preserve_default=False,
        ),
    ]
