# Generated by Django 5.0.1 on 2024-03-04 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0024_parameter_configurationitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameter',
            old_name='configurationItem',
            new_name='transformer',
        ),
    ]
