# Generated by Django 5.0.1 on 2024-03-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0026_remove_transformeritem_alifemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='selectionMode',
            field=models.CharField(choices=[('BOX', 'Box'), ('BRUSH', 'Brush')], default='BOX', max_length=10),
        ),
    ]
