# Generated by Django 5.0.1 on 2024-03-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0027_tool_selectionmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='selectionMode',
            field=models.CharField(choices=[('BOX', 'Box'), ('BRUSH', 'Brush')], max_length=10),
        ),
    ]
